name: 'Pinata Unpin Content'
description: 'Get a list of all pinned content and unpin it'
inputs:
  pinataKey:
    description: 'Pinata Key'
    required: true
  pinataSecret:
    description: 'Pinata Secret'
    required: true
runs:
  using: 'node18'
  main: 'index.js'
